#https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/
version: '3.9'
services: 
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache-cli-dev
    ports: 
      - 8545:8545
    networks:
      - pawningshopdev
    volumes:
      - ganache_volume:/app/ganache-data
    command:
      - --mnemonic
      - indoor neither various team olympic kit middle involve magnet topic history liar
      - --db
      - /app/ganache-data
      - --networkId
      - '5777'
  
  redis:
    image: redis
    container_name: redis-dev
    networks:
      - pawningshopdev
    ports:
      - 6969:6379
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    networks:
      - pawningshopdev
    environment:
    - RABBITMQ_DEFAULT_USER=khanh
    - RABBITMQ_DEFAULT_PASS=handsome
    ports:
      - 5672:5672
      - 15672:15672
    
  mongo:
    image: mongo
    container_name: mongo-dev
    tty: true
    ports:
      - 27018:27018
    volumes:
      - ./mongodb:/auth   
    networks:
      - pawningshopdev
#    command: bash -c "/usr/bin/mongod --replSet rsmongo --keyFile /auth/mongo.key --bind_ip_all --port 27018"
#    command: bash -c "chmod 600 /auth/file.key/mongo.key && chown -R mongodb:mongodb /auth && /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key/mongo.key --bind_ip_all --port 27018"
#    command: bash -c "chmod 600 /auth/file.key/mongo.key && chown -R mongodb:mongodb /auth && tail -F anything"
    command: bash -c "tail -F anything"
  mongo1:
    image: mongo
    container_name: mongo1-dev
    ports:
      - 27019:27019
    volumes:
      - ./mongodb:/auth
    networks:
      - pawningshopdev
    command: bash -c "/usr/bin/mongod --replSet rsmongo --keyFile /auth/mongo.key --bind_ip_all --port 27019"
#    command: bash -c "chmod 600 /auth/file.key/mongo.key && chown -R mongodb:mongodb /auth && /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key/mongo.key --bind_ip_all --port 27019"
#    command: /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key --bind_ip_all --port 27019

  mongo2:
    image: mongo
    container_name: mongo2-dev
    ports:
      - 27020:27020
    volumes:
      - ./mongodb/file.key:/auth/file.key
    networks:
      - pawningshopdev
    command: bash -c "/usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key/mongo.key --bind_ip_all --port 27020"
#    command: bash -c "chmod 600 /auth/file.key/mongo.key && chown -R mongodb:mongodb /auth && /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key/mongo.key --bind_ip_all --port 27020"
#    command: /usr/bin/mongod --replSet rsmongo --keyFile /auth/file.key --bind_ip_all --port 27020

volumes:
  ganache_volume:
    name: ganache_volume_dev
#  mongo_volume:
#    name: mongo_volume_dev
#    external: true

#  mongo_authvolume:
#    name: mongo_authvolume_dev
#    driver_opts:
#      type: none
#      device: /com.docker.devenvironments.code/mongodb/auth/file.key #NOTE needs full path (~ doesn't work)
#      o: bind
#  mongo_datavolume:
#    driver_opts:
#      type: none
#      device: /com.docker.devenvironments.code/mongodb/data #NOTE needs full path (~ doesn't work)
#      o: bind
secrets:
  db_password:
    file: ./db_password.txt
  db_username:
    file: ./db_username.txt
networks: 
  pawningshopdev: